version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TIMEOUT: 10000000
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    networks:
      - app_network

networks:
  app_network:
    external: true